# Generated by Django 5.2.6 on 2025-10-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='fbc12e4566760ab63eaf189c65c3205809f89f3b', max_length=64, unique=True),
        ),
    ]
