# Generated by Django 5.2.6 on 2025-11-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='87d7089b624035cb2d1456019bd9954000f71714', max_length=40, primary_key=True, serialize=False, verbose_name='Key'),
        ),
    ]
