# Generated by Django 5.2.6 on 2025-10-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='baf6c0a32d97cb54361f0fdec96386dbc82946e2', max_length=64, unique=True),
        ),
    ]
