# Generated by Django 5.2.6 on 2025-11-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_token_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='write_enabled',
            field=models.BooleanField(default=True, verbose_name='write enabled'),
        ),
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='b5c6a3476f0bea747d6a6607eb08f47e09646483', max_length=40, primary_key=True, serialize=False, verbose_name='Key'),
        ),
    ]
