# Generated by Django 5.2.6 on 2025-10-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_token_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='865d0da442c278f40caf1a19fed0d8c853b2ddde', max_length=64, unique=True),
        ),
    ]
