# Generated by Django 5.2.6 on 2025-10-29 18:25

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_user_first_name_alter_token_key'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='token',
            managers=[
                ('DoesNotExist', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='a8bd7a228ab216aab1a959ee42941a2d4ccc8474', max_length=64, unique=True),
        ),
    ]
