# Generated by Django 5.2.6 on 2025-10-29 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_token_managers_alter_token_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
