# Generated by Django 5.2.6 on 2025-10-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='ef4ba4c8e75cdd6cb8120d8403ddfadf22e4c847', max_length=40, primary_key=True, serialize=False, verbose_name='Key'),
        ),
    ]
