# Generated by Django 5.2.6 on 2025-10-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_alter_token_key'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='dd71136994d6d4263d98684d3c3bb099604d3dae', max_length=40, primary_key=True, serialize=False, verbose_name='Key'),
        ),
    ]
