# Generated by Django 5.2.6 on 2025-10-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_token_permissions_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='f52312003f6ee69d51037e6963af16403bb4b4bb', max_length=40, primary_key=True, serialize=False, verbose_name='Key'),
        ),
    ]
